[package]
name = "nous-retrieval"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
nous-core.workspace = true
nous-configuration.workspace = true
nous-persistence.workspace = true
nous-object-store.workspace = true
nous-runtime.workspace = true
serde.workspace = true
schemars.workspace = true
serde_json.workspace = true
usearch.workspace = true
tantivy.workspace = true
nalgebra.workspace = true
roaring.workspace = true
arc-swap.workspace = true
blake3.workspace = true
tokio.workspace = true
chrono.workspace = true
async-trait.workspace = true
sqlx.workspace = true
tempfile.workspace = true

[lints]
workspace = true
