[package]
name = "nous-subject"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
nous-core.workspace = true
nous-persistence.workspace = true
nous-object-store.workspace = true
nous-configuration.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
chrono.workspace = true
uuid.workspace = true
sqlx.workspace = true

[lints]
workspace = true
