[package]
name = "nous-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
nous-authority-store.workspace = true
nous-object-store.workspace = true
nous-subject-core.workspace = true
nous-cognitive-runtime.workspace = true
nous-cognitive-retrieval.workspace = true
nous-material-service.workspace = true
nous-serving.workspace = true
nous-core.workspace = true
nous-material.workspace = true
nous-memory-service.workspace = true
nous-memory-domain.workspace = true
nous-self-service.workspace = true
nous-self-domain.workspace = true
nous-configuration-service.workspace = true
nous-social-service.workspace = true
nous-social-domain.workspace = true
tokio.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
futures.workspace = true
postgresql_embedded.workspace = true
chrono.workspace = true

nous-protocol.workspace = true
blake3.workspace = true
prost-types.workspace = true
prost.workspace = true
tonic.workspace = true
tonic-prost.workspace = true
tonic-health.workspace = true
tokio-stream.workspace = true
sqlx.workspace = true

[dev-dependencies]
tempfile.workspace = true
postgresql_embedded.workspace = true
sqlx.workspace = true
nous-self-domain.workspace = true

[lints]
workspace = true
